version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network

  app:
    build:
      context: node
    image: rafaelp777/node-app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db

  migration:
    image: rafaelp777/node-app
    container_name: migration
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: [
      "npm",
      "run",
      "migrate"
    ]
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db
  
  nginx:
    build:
      context: nginx
    image: rafaelp777/nginx-node
    container_name: nginx-node
    tty: true
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
